import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/foundation.dart';

/// The one-off effects.
enum Sfx {
  mark('mark.wav'),
  remove('remove.wav'),
  error('error.wav'),
  win('win.wav'),
  boom('boom.wav'),
  star1('star_1.wav'),
  star2('star_2.wav'),
  star3('star_3.wav');

  const Sfx(this.file);

  final String file;
}

/// Plays the game's sounds.
///
/// Every effect is generated by `tool/build_sounds.dart` rather than sourced,
/// so there is nothing to license and the repository stays self-contained.
///
/// Failures are swallowed on purpose. Audio is the least important thing the
/// app does, and a device with no working audio route, or a test environment
/// with no plugin at all, must not take the game down with it. After the first
/// failure the service stops trying.
class SoundService {
  SoundService({this.enabled = true});

  /// Replaceable so tests and previews can drop in a silent one.
  static SoundService instance = SoundService();

  /// Steps in the placement ladder, matching the generated files.
  static const int ladderSteps = 12;

  /// How many players to keep. Enough that a placement, a mark and a win can
  /// overlap without cutting each other off.
  static const int _voices = 4;

  bool enabled;

  final List<AudioPlayer> _players = [];
  var _next = 0;
  var _available = true;
  var _ready = false;

  /// Creates the players. Safe to call more than once.
  Future<void> warmUp() async {
    if (_ready || !_available) return;
    _ready = true;
    try {
      for (var i = 0; i < _voices; i++) {
        final player = AudioPlayer()
          ..setReleaseMode(ReleaseMode.stop)
          ..setPlayerMode(PlayerMode.lowLatency);
        _players.add(player);
      }
    } catch (error) {
      _available = false;
      debugPrint('Sound unavailable, continuing without it: $error');
    }
  }

  /// The note for the nth mine placed, climbing a major scale.
  ///
  /// Pitch follows how many mines are on the board, not whether they are
  /// correct. Tying it to correctness would quietly tell the player they had
  /// gone wrong, which is the game giving away its own answer.
  void playPlacement(int minesPlaced) {
    final step = (minesPlaced - 1).clamp(0, ladderSteps - 1);
    _play('place_${step.toString().padLeft(2, '0')}.wav');
  }

  void play(Sfx sfx) => _play(sfx.file);

  void _play(String file) {
    if (!enabled || !_available || _players.isEmpty) return;
    try {
      final player = _players[_next];
      _next = (_next + 1) % _players.length;
      // Deliberately not awaited: a sound must never delay a tap.
      player.play(AssetSource('sounds/$file'), volume: 0.85).catchError((_) {});
    } catch (error) {
      _available = false;
      debugPrint('Sound failed, continuing without it: $error');
    }
  }

  Future<void> dispose() async {
    for (final player in _players) {
      try {
        await player.dispose();
      } catch (_) {
        // Nothing useful to do while tearing down.
      }
    }
    _players.clear();
    _ready = false;
  }
}

/// A sound service that does nothing, for tests and previews.
class SilentSoundService extends SoundService {
  SilentSoundService() : super(enabled: false);

  @override
  Future<void> warmUp() async {}

  @override
  void play(Sfx sfx) {}

  @override
  void playPlacement(int minesPlaced) {}
}
